### ISSUE TITLE
ink-flipper-analyzer

### ISSUE THREAD

**Issue by ganesh1233456** [ink-analyzer/ink-analyzer#1]
hey, @davidsemakula I was testing ink-analyzer for [simple-flipper](https://github.com/ganesh1233456/ink-flipper-analyzer) ink project but I wonder whether include analysis code inside test module or where? Can you please suggest me where do I add analyer code?

**Comment by davidsemakula** [comment]
Hi @ganesh1233456 
Thanks for your interest in the project 🙂 

So for some context, this library is meant to be building block for adding ink! language support to developer tools. 
The first target is going to be IDEs and code editors to add features like:
- diagnostic errors and warnings based on ink! semantic rules (e.g. exactly one `#[ink(storage)]` struct, at least one `#[ink(message)]` method and the same for `#[ink(constructor)]`, ink! attributes should be applied to items of the correct type e.t.c.) - a few of these are already, checkout the [readme](./README.md#1-analysis)
- code completion suggestions and hover content support for ink! attribute arguments (e.g. `#[ink(payable)]`) which is mostly missing right now (proc macros like `#[ink::contract]` are mostly fine here)
- code/intent actions for adding ink! attributes to items 

And more, may be even security and vulnerability detection related analysis.

For this, there will be additional components for the project like a [language server](https://microsoft.github.io/language-server-protocol/) implementation that use this library for the actual semantic analysis and a VS Code extension that will use the language server (more repos for these will be added soon 🙂).

So think of using ink! analyzer similar to how you likely use [rust analyzer](https://rust-analyzer.github.io/) now, ink! analyzer just adds ink! support that rust-analyzer can't do because its not aware of ink!'s domain specific semantic rules.

So you'll mostly likely be using ink! analyzer from stuff like your IDE or code editor as an extension/plugin for improvement language support, as part of your linter or CI workflow e.t.c.

That being said, there's technically nothing that stops you from using it directly inside a test module if that makes sense for project or just to play around with it. As you can see from the [usage example in the readme](./README.md#usage), for diagnostics, the library takes the smart contract code text as input, so you need to read than in first, so a snippet would look like

```rust
// --snip--

#[cfg(test)]
mod tests {
    use ink_analyzer::Analysis;

    #[test]
    fn no_semantic_errors() {
        // read current file as a string literal
        let code = include_str!(file!());

        // run diagnostics
        let diagnostics = Analysis.diagnostics(code);

        // fail test if any diagnostics failed
        assert!(diagnostics.is_empty());
    }
}
```

More documentation about the whole project & its architecture and tooling improvements will be coming through out next week (and the coming weeks).

This is a bit more than what you asked but I hope it answers your question with some context 🙂

**Comment by ganesh1233456** [comment]
ya it's more that I asked and thank you for this explanation😀. it's awesome idea for ink! smart contract. I am trying to understanding your code and It is really cool.
